% Get debris-supply rate uncertainties 

% This function calculates debris-supply rate and englacial debris content 
% uncertainties, as described by McCarthy et al (2022)
%
% Michael McCarthy, November 2022 (michael.mccarthy@wsl.ch)

function [sigq_ds,sigc_edA,sigc_ed] = getdsrerror(q_edA,sigQ_sdA_out,...
    Q_sdA_out,q_edI,q_edA_d,A_dA,A_dI,rho_d,rho_r,M_A,sigM_A,q_ds,...
    c_edA,c_ed)

% Get active debris emergence rate uncertainty
sigq_edA = abs(q_edA)*sqrt((sigQ_sdA_out/Q_sdA_out)^2+...
    0.1^2);

% Get inactive debris emergence rate uncertainty
sigq_edI = abs(q_edI)*sigq_edA/q_edA;

% Get uncertainty of volume flux of englacial debris to glacier surface
sigq_edA_d = sqrt((q_edA*A_dA*0.1)^2+...
    (A_dA*sigq_edA)^2+...
    (q_edI*A_dI*0.1)^2+...
    (A_dI*sigq_edI)^2);

% Get DSR uncertainty
sigq_ds = abs(q_ds)*sqrt((100/rho_d)^2+...
    (sigq_edA_d/q_edA_d)^2+...
    (100/rho_r)^2+...
    0.1^2);

% Get englacial debris content uncertainty in ablation area
covM_Aq_edA = sqrt((sigM_A^2)*(sigq_edA^2));
sigc_edA = abs(c_edA)*sqrt((sigq_edA/q_edA)^2+...
    (100/rho_d)^2+...
    (sigM_A/M_A)^2+...
    (100/rho_r)^2-...
    2*covM_Aq_edA/(M_A*q_edA));

% Get englacial debris content uncertainty of glacier
sigc_ed = abs(c_ed)*sqrt((sigc_edA/c_edA)^2+...
    (60/850)^2); % Glacier ice uncertainties from Huss (2013)

end